// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm3qxYpsm17Qaac06px_CW6P3TjaZ8ceA',
    appId: '1:1052841639210:web:a16c79d29d797a1f2ef253',
    messagingSenderId: '1052841639210',
    projectId: 'diaai1',
    authDomain: 'diaai1.firebaseapp.com',
    storageBucket: 'diaai1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGkE7nnSnIt3geaUxzhjes22NBBW0D5Hg',
    appId: '1:1052841639210:android:cc5d1370c4e25f522ef253',
    messagingSenderId: '1052841639210',
    projectId: 'diaai1',
    storageBucket: 'diaai1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZgv5Qm4GWuL6ILNrsKA9y6-0GhFhDJIA',
    appId: '1:1052841639210:ios:d9208f02d9eb153a2ef253',
    messagingSenderId: '1052841639210',
    projectId: 'diaai1',
    storageBucket: 'diaai1.firebasestorage.app',
    iosBundleId: 'com.DiaAI.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm3qxYpsm17Qaac06px_CW6P3TjaZ8ceA',
    appId: '1:1052841639210:web:c8aa9884c99369a32ef253',
    messagingSenderId: '1052841639210',
    projectId: 'diaai1',
    authDomain: 'diaai1.firebaseapp.com',
    storageBucket: 'diaai1.firebasestorage.app',
  );
}
